spring:
  # 对应 RedisProperties 类
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456 # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    database: 0 # Redis 数据库号，默认为 0 。
    timeout: 5000 # Redis 连接超时时间，单位：毫秒。
  # 对应 SecurityProperties 类
  security:
    user: # 配置内存中，可登录的用户名和密码
      name: admin
      password: admin
