spring:
  data:
    # MongoDB 配置项，对应 MongoProperties 类
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
      username: test
      # 密码必须使用字符串且是单引号，否则报错
      password: 'test'
      # 上述属性，也可以只配置 uri
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456 # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    database: 0 # Redis 数据库号，默认为 0 。
    timeout: 0 # Redis 连接超时时间，单位：毫秒。

  # Elasticsearch 配置项
  elasticsearch:
    uris: 127.0.0.1:9200
  r2dbc:
    url: mysql://127.0.0.1:3306/test
    username: root
    password: root

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG # 打印 mongodb 操作的具体语句。生产环境下，不建议开启。
